name: memory_usage
version: 0.1.1
description: A framework for memory usage tracking, snapshotting and optimization.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/memory_usage

environment:
  sdk: ^3.2.0

dependencies:
  collection: ^1.18.0
  meta: ^1.12.0
  path: ^1.8.3

dev_dependencies:
  dart_flutter_team_lints: ^2.1.0
  layerlens: ^1.0.16
  leak_tracker:
    path: ../leak_tracker
  test: ^1.16.0
